version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: user
        uid: 1000
    container_name: fiance
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - fiance

  db:
    image: mysql:latest
    container_name: db-fiance
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:  ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_USER:  ${DB_USERNAME}
    networks:
      - fiance

  nginx:
    image: nginx:alpine
    container_name: nginx-inventaire
    restart: unless-stopped
    ports:
      - "8000:80" # Port 81 pour nginx
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - fiance

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_USER:  ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Assurez-vous de définir la même valeur que pour MYSQL_ROOT_PASSWORD dans le service db
    ports:
      - "8080:82" # Port 8080 pour phpMyAdmin
    networks:
      - fiance

networks:
  fiance:
    driver: bridge
