version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: financeapp
      DB_USERNAME: kev
      DB_PASSWORD: Ko9_Hu3_Fap6

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ko9_Hu3_Fap6
      MYSQL_DATABASE: financeapp
      MYSQL_USER: kev
      MYSQL_PASSWORD: Ko9_Hu3_Fap6

